# Global params
INITIAL_WAIT = 3
TR = 1.49
FINAL_WAIT = 10
TASK_COUNTS = {"DMS":2, "CTXDM": 2, "INTERDMS2": 3, "1BACK": 2, "2BACK": 2} 

# Trial Times
DMS_TRIAL = 9.45
INTERDMS_TRIAL = 25.85
CTXDM_TRIAL = 14.42
ONEBACK_TRIAL = 24.36
TWOBACK_TRIAL = 24.36

"""
Assuming 4hours of in scanner time, 1h per session for 4 sessions
"""
# DMS_A_LO
DMS_A_LO_N_TRIALS = 11
DMS_A_LO_BLOCK_TIME = DMS_A_LO_N_TRIALS * DMS_TRIAL + INITIAL_WAIT + FINAL_WAIT

# DMS_O_LO
DMS_O_LO_N_TRIALS = 11
DMS_O_LO_BLOCK_TIME = DMS_O_LO_N_TRIALS * DMS_TRIAL + INITIAL_WAIT + FINAL_WAIT

# CTXDM_OCL
CTXDM_OCL_N_TRIALS = 9
CTXDM_OCL_BLOCK_TIME = CTXDM_OCL_N_TRIALS * CTXDM_TRIAL + INITIAL_WAIT + FINAL_WAIT

# CTXDM_LOL
CTXDM_LOL_N_TRIALS = 9
CTXDM_LOL_BLOCK_TIME = CTXDM_LOL_N_TRIALS * CTXDM_TRIAL + INITIAL_WAIT + FINAL_WAIT

# INTERDMS_ABBCCA_LOC
INTERDMS_ABBCCA_LOC_N_TRIALS = 7
INTERDMS_ABBCCA_LOC_BLOCK_TIME = INTERDMS_ABBCCA_LOC_N_TRIALS * INTERDMS_TRIAL + INITIAL_WAIT + FINAL_WAIT

# INTERDMS_ABBCCA_CTG
INTERDMS_ABBCCA_CTG_N_TRIALS = 7
INTERDMS_ABBCCA_CTG_BLOCK_TIME = INTERDMS_ABBCCA_CTG_N_TRIALS * INTERDMS_TRIAL + INITIAL_WAIT + FINAL_WAIT

# INTERDMS_ABCABC_LOC
INTERDMS_ABCABC_LOC_N_TRIALS = 7
INTERDMS_ABCABC_LOC_BLOCK_TIME = INTERDMS_ABCABC_LOC_N_TRIALS * INTERDMS_TRIAL + INITIAL_WAIT + FINAL_WAIT       
  
# 1BACK_LOC
ONEBACK_LOC_N_TRIALS = 10
ONEBACK_LOC_BLOCK_TIME = ONEBACK_LOC_N_TRIALS * ONEBACK_TRIAL + INITIAL_WAIT + FINAL_WAIT

# 1BACK_CTG
ONEBACK_CTG_N_TRIALS = 10
ONEBACK_CTG_N_TRIALS = ONEBACK_CTG_N_TRIALS * ONEBACK_TRIAL + INITIAL_WAIT + FINAL_WAIT

# 2BACK_LOC
TWOBACK_LOC_N_TRIALS = 10
TWOBACK_LOC_BLOCK_TIME = TWOBACK_LOC_N_TRIALS * TWOBACK_TRIAL + INITIAL_WAIT + FINAL_WAIT
    
# 2BACK_CTG
TWOBACK_CTG_N_TRIALS = 10
TWOBACK_CTG_BLOCK_TIME = TWOBACK_CTG_N_TRIALS * TWOBACK_TRIAL + INITIAL_WAIT + FINAL_WAIT


"""
Print Estimated number of TCs per task
"""
print(f"Estimated number of TCs per task:")
print(f"DMS_A_LO: {DMS_A_LO_BLOCK_TIME} seconds, or {DMS_A_LO_BLOCK_TIME/TR} TRs ")
print(f"DMS_O_LO: {DMS_O_LO_BLOCK_TIME} seconds, or {DMS_O_LO_BLOCK_TIME/TR} TRs ")
print(f"CTXDM_OCL: {CTXDM_OCL_BLOCK_TIME} seconds, or {CTXDM_OCL_BLOCK_TIME/TR} TRs ")
print(f"CTXDM_LOL: {CTXDM_LOL_BLOCK_TIME} seconds, or {CTXDM_LOL_BLOCK_TIME/TR} TRs ")
print(f"INTERDMS_ABBCCA_LOC: {INTERDMS_ABBCCA_LOC_BLOCK_TIME} seconds, or {INTERDMS_ABBCCA_LOC_BLOCK_TIME/TR} TRs ")
print(f"INTERDMS_ABBCCA_CTG: {INTERDMS_ABBCCA_CTG_BLOCK_TIME} seconds, or {INTERDMS_ABBCCA_CTG_BLOCK_TIME/TR} TRs ")
print(f"INTERDMS_ABCABC_LOC: {INTERDMS_ABCABC_LOC_BLOCK_TIME} seconds, or {INTERDMS_ABCABC_LOC_BLOCK_TIME/TR} TRs ")
print(f"1BACK_LOC: {ONEBACK_LOC_BLOCK_TIME} seconds, or {ONEBACK_LOC_BLOCK_TIME/TR} TRs ")
print(f"1BACK_CTG: {ONEBACK_CTG_N_TRIALS} seconds, or {ONEBACK_CTG_N_TRIALS/TR} TRs ")
print(f"2BACK_LOC: {TWOBACK_LOC_BLOCK_TIME} seconds, or {TWOBACK_LOC_BLOCK_TIME/TR} TRs ")
print(f"2BACK_CTG: {TWOBACK_CTG_BLOCK_TIME} seconds, or {TWOBACK_CTG_BLOCK_TIME/TR} TRs ")  
