# Global params
INITIAL_WAIT = 3
FINAL_WAIT = 10
TASK_COUNTS = {"DMS":2, "CTXDM": 2, "INTERDMS2": 3, "1BACK": 2, "2BACK": 2} 

# Trial Times
DMS_TRIAL = 9.45
INTERDMS_TRIAL = 25.85
CTXDM_TRIAL = 14.42
ONEBACK_TRIAL = 24.36
TWOBACK_TRIAL = 24.36
ONEBACK_STIM_PAIR = ONEBACK_TRIAL / 4
TWOBACK_STIM_PAIR = TWOBACK_TRIAL / 4


"""
Assuming 4hours of in scanner time, 1h per session for 4 sessions
"""
# DMS_A_LO
N_BLOCKS_DMS_A_LO = 1
DMS_A_LO_N_TRIALS = 10
DMS_A_LO_BLOCK_TIME = DMS_A_LO_N_TRIALS * DMS_TRIAL + INITIAL_WAIT + FINAL_WAIT

# DMS_O_LO
N_BLOCKS_DMS_O_LO = 1
DMS_O_LO_N_TRIALS = 10 
DMS_O_LO_BLOCK_TIME = DMS_O_LO_N_TRIALS * DMS_TRIAL + INITIAL_WAIT + FINAL_WAIT

# CTXDM_OCL
N_BLOCKS_CTXDM_OCL = 1
CTXDM_OCL_N_TRIALS = 6
CTXDM_OCL_BLOCK_TIME = CTXDM_OCL_N_TRIALS * CTXDM_TRIAL + INITIAL_WAIT + FINAL_WAIT

# CTXDM_LOL
N_BLOCKS_CTXDM_LOL = 1
CTXDM_LOL_N_TRIALS = 6
CTXDM_LOL_BLOCK_TIME = CTXDM_LOL_N_TRIALS * CTXDM_TRIAL + INITIAL_WAIT + FINAL_WAIT

# INTERDMS_ABBCCA_LOC
N_BLOCKS_INTERDMS_ABBCCA_LOC = 1
INTERDMS_ABBCCA_LOC_N_TRIALS = 6
INTERDMS_ABBCCA_LOC_BLOCK_TIME = INTERDMS_ABBCCA_LOC_N_TRIALS * INTERDMS_TRIAL + INITIAL_WAIT + FINAL_WAIT

# INTERDMS_ABBCCA_CTG
N_BLOCKS_INTERDMS_ABBCCA_CTG = 1
INTERDMS_ABBCCA_CTG_N_TRIALS = 6
INTERDMS_

INTERDMS_ABBCCA_CTG_N_TRIALS = 6
INTERDMS_ABBCCA_CTG_BLOCK_TIME = INTERDMS_ABBCCA_CTG_N_TRIALS * INTERDMS_TRIAL + INITIAL_WAIT + FINAL_WAIT

# INTERDMS_ABCABC_LOC
N_BLOCKS_INTERDMS_ABCABC_LOC = 1
INTERDMS_ABCABC_LOC_BLOCKS_TIME = BLOCKS_TIME_PER_TASK / TASK_COUNTS["INTERDMS2"] - (INITIAL_WAIT + FINAL_WAIT) * N_BLOCKS_INTERDMS_ABCABC_LOC
INTERDMS_ABCABC_LOC_N_TRIALS = int(INTERDMS_ABCABC_LOC_BLOCKS_TIME / INTERDMS_TRIAL)            
  
# 1BACK_LOC
N_BLOCKS_1BACK_LOC = 1
ONEBACK_LOC_BLOCKS_TIME = BLOCKS_TIME_PER_TASK / TASK_COUNTS["1BACK"] - (INITIAL_WAIT + FINAL_WAIT) * N_BLOCKS_1BACK_LOC
MAX_ONEBACK_LOC_N_TRIALS = int(ONEBACK_LOC_BLOCKS_TIME / ONEBACK_STIM_PAIR)

# 1BACK_CTG
N_BLOCKS_1BACK_CTG = 1
ONEBACK_CTG_BLOCKS_TIME = BLOCKS_TIME_PER_TASK / TASK_COUNTS["1BACK"] - (INITIAL_WAIT + FINAL_WAIT) * N_BLOCKS_1BACK_CTG
MAX_ONEBACK_CTG_N_TRIALS = int(ONEBACK_CTG_BLOCKS_TIME / ONEBACK_STIM_PAIR)

# 2BACK_LOC
N_BLOCKS_2BACK_LOC = 1
ONEBACK_LOC_BLOCKS_TIME = BLOCKS_TIME_PER_TASK / TASK_COUNTS["1BACK"] - (INITIAL_WAIT + FINAL_WAIT) * N_BLOCKS_1BACK_LOC
MAX_ONEBACK_LOC_N_TRIALS = int(ONEBACK_LOC_BLOCKS_TIME / ONEBACK_STIM_PAIR)
    
# 2BACK_CTG
N_BLOCKS_1BACK_CTG = 1
ONEBACK_CTG_BLOCKS_TIME = BLOCKS_TIME_PER_TASK / TASK_COUNTS["1BACK"] - (INITIAL_WAIT + FINAL_WAIT) * N_BLOCKS_1BACK_CTG
MAX_ONEBACK_CTG_N_TRIALS = int(ONEBACK_CTG_BLOCKS_TIME / ONEBACK_STIM_PAIR)


"""
Print Estimated number of TCs per task
"""
print(f"Estimated number of TCs per task:")
print(f"DMS_A_LO: {DMS_A_LO_N_TRIALS} TCs  ({int(DMS_A_LO_N_TRIALS/N_BLOCKS_DMS_A_LO)} per block)")
print(f"DMS_O_LO: {DMS_O_LO_N_TRIALS} TCs  ({int(DMS_O_LO_N_TRIALS/N_BLOCKS_DMS_O_LO)} per block)")
print(f"CTXDM_OCL: {CTXDM_OCL_N_TRIALS} TCs  ({int(CTXDM_OCL_N_TRIALS/N_BLOCKS_CTXDM_OCL)} per block)")
print(f"CTXDM_LOL: {CTXDM_LOL_N_TRIALS} TCs  ({int(CTXDM_LOL_N_TRIALS/N_BLOCKS_CTXDM_LOL)} per block)")
print(f"INTERDMS_ABBCCA_LOC: {INTERDMS_ABBCCA_LOC_N_TRIALS} TCs  ({int(INTERDMS_ABBCCA_LOC_N_TRIALS/N_BLOCKS_INTERDMS_ABBCCA_LOC)} per block)")
print(f"INTERDMS_ABBCCA_CTG: {INTERDMS_ABBCCA_CTG_N_TRIALS} TCs  ({int(INTERDMS_ABBCCA_CTG_N_TRIALS/N_BLOCKS_INTERDMS_ABBCCA_CTG)} per block)")
print(f"INTERDMS_ABCABC_LOC: {INTERDMS_ABCABC_LOC_N_TRIALS} TCs  ({int(INTERDMS_ABCABC_LOC_N_TRIALS/N_BLOCKS_INTERDMS_ABCABC_LOC)} per block)")
print(f"1BACK_LOC: {MAX_ONEBACK_LOC_N_TRIALS} MAX TCs  ({int(MAX_ONEBACK_LOC_N_TRIALS/N_BLOCKS_1BACK_LOC)})")
print(f"1BACK_CTG: {MAX_ONEBACK_CTG_N_TRIALS} MAX TCs  ({int(MAX_ONEBACK_CTG_N_TRIALS/N_BLOCKS_1BACK_CTG)})")
print(f"2BACK_LOC: {MAX_ONEBACK_LOC_N_TRIALS} MAX TCs  ({int(MAX_ONEBACK_LOC_N_TRIALS/N_BLOCKS_1BACK_LOC)})")
print(f"2BACK_CTG: {MAX_ONEBACK_CTG_N_TRIALS} MAX TCs  ({int(MAX_ONEBACK_CTG_N_TRIALS/N_BLOCKS_1BACK_CTG)})")
