# Global params
INITIAL_WAIT = 3
FINAL_WAIT = 10
TASK_COUNTS = {"CTXDM": 2, "INTERDMS": 6, "1BACK": 3}

# Trial Times
INTERDMS_TRIAL = 17.65
CTXDM_TRIAL = 14.42
ONEBACK_TRIAL = 29.3
ONEBACK_STIM_PAIR = ONEBACK_TRIAL / 5  # assuming 5 stimuli per trial

"""
Assuming 4hours of in scanner time, 1h per session for 4 sessions
"""
# Session times
SESSION_TIME = 3600  # seconds (1 hour)
LOST_TIME_ESTIMATE = 900  # seconds (15 minutes)
BLOCKS_TIME = SESSION_TIME - LOST_TIME_ESTIMATE  # seconds (2700 seconds, 45 minutes)
BLOCKS_TIME_PER_TASK = BLOCKS_TIME / 3  # seconds (900 seconds, 15 minutes)

# CTXDM_COL
N_BLOCKS_CTXDM_COL = 2
CTXDM_COL_BLOCKS_TIME = BLOCKS_TIME_PER_TASK / TASK_COUNTS["CTXDM"] - (INITIAL_WAIT + FINAL_WAIT) * N_BLOCKS_CTXDM_COL  # seconds (444 seconds)
CTXDM_COL_N_TRIALS = int(CTXDM_COL_BLOCKS_TIME / CTXDM_TRIAL)  

# CTXDM_LCO
N_BLOCKS_CTXDM_LCO = 2
CTXDM_LCO_BLOCKS_TIME = BLOCKS_TIME_PER_TASK / TASK_COUNTS["CTXDM"] - (INITIAL_WAIT + FINAL_WAIT) * N_BLOCKS_CTXDM_LCO  # seconds (444 seconds)
CTXDM_LCO_N_TRIALS = int(CTXDM_LCO_BLOCKS_TIME / CTXDM_TRIAL)  

# INTERDMS_ABAB_LOC
N_BLOCKS_INTERDMS_ABAB_LOC = 1
INTERDMS_ABAB_LOC_BLOCKS_TIME = BLOCKS_TIME_PER_TASK / TASK_COUNTS["INTERDMS"] - (INITIAL_WAIT + FINAL_WAIT) * N_BLOCKS_INTERDMS_ABAB_LOC  
INTERDMS_ABAB_LOC_N_TRIALS = int(INTERDMS_ABAB_LOC_BLOCKS_TIME / INTERDMS_TRIAL)

# INTERDMS_ABBA_LOC
N_BLOCKS_INTERDMS_ABBA_LOC = 1
INTERDMS_ABBA_LOC_BLOCKS_TIME = BLOCKS_TIME_PER_TASK / TASK_COUNTS["INTERDMS"] - (INITIAL_WAIT + FINAL_WAIT) * N_BLOCKS_INTERDMS_ABBA_LOC  
INTERDMS_ABBA_LOC_N_TRIALS = int(INTERDMS_ABBA_LOC_BLOCKS_TIME / INTERDMS_TRIAL)    

# INTERDMS_ABAB_CTG
N_BLOCKS_INTERDMS_ABAB_CTG = 1
INTERDMS_ABAB_CTG_BLOCKS_TIME = BLOCKS_TIME_PER_TASK / TASK_COUNTS["INTERDMS"] - (INITIAL_WAIT + FINAL_WAIT) * N_BLOCKS_INTERDMS_ABAB_CTG
INTERDMS_ABAB_CTG_N_TRIALS = int(INTERDMS_ABAB_CTG_BLOCKS_TIME / INTERDMS_TRIAL)

# INTERDMS_ABBA_CTG
N_BLOCKS_INTERDMS_ABBA_CTG = 1
INTERDMS_ABBA_CTG_BLOCKS_TIME = BLOCKS_TIME_PER_TASK / TASK_COUNTS["INTERDMS"] - (INITIAL_WAIT + FINAL_WAIT) * N_BLOCKS_INTERDMS_ABBA_CTG
INTERDMS_ABBA_CTG_N_TRIALS = int(INTERDMS_ABBA_CTG_BLOCKS_TIME / INTERDMS_TRIAL)    

# INTERDMS_ABAB_OBJ
N_BLOCKS_INTERDMS_ABAB_OBJ = 1
INTERDMS_ABAB_OBJ_BLOCKS_TIME = BLOCKS_TIME_PER_TASK / TASK_COUNTS["INTERDMS"] - (INITIAL_WAIT + FINAL_WAIT) * N_BLOCKS_INTERDMS_ABAB_OBJ
INTERDMS_ABAB_OBJ_N_TRIALS = int(INTERDMS_ABAB_OBJ_BLOCKS_TIME / INTERDMS_TRIAL)            

# INTERDMS_ABBA_OBJ
N_BLOCKS_INTERDMS_ABBA_OBJ = 1
INTERDMS_ABBA_OBJ_BLOCKS_TIME = BLOCKS_TIME_PER_TASK / TASK_COUNTS ["INTERDMS"] - (INITIAL_WAIT + FINAL_WAIT) * N_BLOCKS_INTERDMS_ABBA_OBJ
INTERDMS_ABBA_OBJ_N_TRIALS = int(INTERDMS_ABBA_OBJ_BLOCKS_TIME / INTERDMS_TRIAL)    

# 1BACK_LOC
N_BLOCKS_1BACK_LOC = 1
ONEBACK_LOC_BLOCKS_TIME = BLOCKS_TIME_PER_TASK / TASK_COUNTS["1BACK"] - (INITIAL_WAIT + FINAL_WAIT) * N_BLOCKS_1BACK_LOC
MAX_ONEBACK_LOC_N_TRIALS = int(ONEBACK_LOC_BLOCKS_TIME / ONEBACK_STIM_PAIR)

# 1BACK_CTG
N_BLOCKS_1BACK_CTG = 1
ONEBACK_CTG_BLOCKS_TIME = BLOCKS_TIME_PER_TASK / TASK_COUNTS["1BACK"] - (INITIAL_WAIT + FINAL_WAIT) * N_BLOCKS_1BACK_CTG
MAX_ONEBACK_CTG_N_TRIALS = int(ONEBACK_CTG_BLOCKS_TIME / ONEBACK_STIM_PAIR)

# 1BACK_OBJ
N_BLOCKS_1BACK_OBJ = 1
ONEBACK_OBJ_BLOCKS_TIME = BLOCKS_TIME_PER_TASK / TASK_COUNTS["1BACK"] - (INITIAL_WAIT + FINAL_WAIT) * N_BLOCKS_1BACK_OBJ
MAX_ONEBACK_OBJ_N_TRIALS = int(ONEBACK_OBJ_BLOCKS_TIME / ONEBACK_STIM_PAIR)     

"""
Print Estimated number of TCs per task
"""
print(f"Estimated number of TCs per task:")
print(f"CTXDM_COL: {CTXDM_COL_N_TRIALS} TCs  ({int(CTXDM_COL_N_TRIALS/N_BLOCKS_CTXDM_COL)} per block)")
print(f"CTXDM_LCO: {CTXDM_LCO_N_TRIALS} TCs  ({int(CTXDM_LCO_N_TRIALS/N_BLOCKS_CTXDM_LCO)} per block)")
print(f"INTERDMS_ABAB_LOC: {INTERDMS_ABAB_LOC_N_TRIALS} TCs  ({int(INTERDMS_ABAB_LOC_N_TRIALS/N_BLOCKS_INTERDMS_ABAB_LOC)} per block)")
print(f"INTERDMS_ABBA_LOC: {INTERDMS_ABBA_LOC_N_TRIALS} TCs  ({int(INTERDMS_ABBA_LOC_N_TRIALS/N_BLOCKS_INTERDMS_ABBA_LOC)} per block)")
print(f"INTERDMS_ABAB_CTG: {INTERDMS_ABAB_CTG_N_TRIALS} TCs  ({int(INTERDMS_ABAB_CTG_N_TRIALS/N_BLOCKS_INTERDMS_ABAB_CTG)} per block)")
print(f"INTERDMS_ABBA_CTG: {INTERDMS_ABBA_CTG_N_TRIALS} TCs  ({int(INTERDMS_ABBA_CTG_N_TRIALS/N_BLOCKS_INTERDMS_ABBA_CTG)} per block)")
print(f"INTERDMS_ABAB_OBJ: {INTERDMS_ABAB_OBJ_N_TRIALS} TCs  ({int(INTERDMS_ABAB_OBJ_N_TRIALS/N_BLOCKS_INTERDMS_ABAB_OBJ)} per block)")
print(f"INTERDMS_ABBA_OBJ: {INTERDMS_ABBA_OBJ_N_TRIALS} TCs  ({int(INTERDMS_ABBA_OBJ_N_TRIALS/N_BLOCKS_INTERDMS_ABBA_OBJ)} per block)") 
print(f"1BACK_LOC: {MAX_ONEBACK_LOC_N_TRIALS} MAX TCs  ({int(MAX_ONEBACK_LOC_N_TRIALS/N_BLOCKS_1BACK_LOC)})")
print(f"1BACK_CTG: {MAX_ONEBACK_CTG_N_TRIALS} MAX TCs  ({int(MAX_ONEBACK_CTG_N_TRIALS/N_BLOCKS_1BACK_CTG)})")
print(f"1BACK_OBJ: {MAX_ONEBACK_OBJ_N_TRIALS} MAX TCs  ({int(MAX_ONEBACK_OBJ_N_TRIALS/N_BLOCKS_1BACK_OBJ)})")   